### ISSUE TITLE
Support additional descriptions on Field

### ISSUE THREAD

**Issue by aalmiray** [dlemmermann/formsfx#18]
Similar to https://github.com/dlemmermann/PreferencesFX/issues/23 sometimes you'd like additional text to be displayed under a Field's name or it's renderer. This text may be used as a hint to the user to let them know what data may be entered as the Field's value.

It may be worth using `Node` as a type instead of just `String` as this would allow for additional elements (such as icons) to be embedded in the description.

I propose to add two more properties to Field: `labelDescription(Node)` and `valueDescription(Node)`/`fieldDescription(Node)`.

**Comment by dlemmermann** [comment]
Sounds good to me. As long as it does not break the current API obviously.

**Comment by aalmiray** [comment]
Fixed.
