### ISSUE TITLE
JDK 11 compatible

### ISSUE THREAD

**Issue by ChanduCB** [dlemmermann/formsfx#38]
I tried maven build for this application using jdk 11 but its not working

**Comment by dlemmermann** [comment]
Nobody will be able to help you if you do not provide a description of the problems you are facing.

**Comment by ChanduCB** [comment]
Apologies for my description , am trying to run  application in eclipse  with JDK 11 it was not working, then i tried to run mvn clean install it is also failing. Is the application JDK 11 compatible? 
we are getting following error please advice.
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/IntegerField.java:[47,65] cannot find symbol
  symbol:   class SimpleIntegerProperty
  location: class com.dlsc.formsfx.model.structure.IntegerField
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[64,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[80,15] cannot find symbol
  symbol:   class StringConverter
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[93,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[94,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[99,19] cannot find symbol
  symbol:   class InvalidationListener
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[172,21] cannot find symbol
  symbol:   class StringConverter
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[191,21] cannot find symbol
  symbol:   class StringConverter
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[450,12] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[80,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[81,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[90,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[91,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[100,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[101,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[107,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[108,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[109,21] cannot find symbol
  symbol:   class BooleanProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[110,21] cannot find symbol
  symbol:   class BooleanProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[116,21] cannot find symbol
  symbol:   class BooleanProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[117,21] cannot find symbol
  symbol:   class BooleanProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[122,21] cannot find symbol
  symbol:   class StringProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[123,21] cannot find symbol
  symbol:   class ListProperty
  location: class com.dlsc.formsfx.model.structure.Field<F>
[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] FormsFX ........................................... FAILURE [34.899s]
[INFO] formsfx ........................................... SKIPPED
[INFO] formsfx-demo ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.418s
[INFO] Finished at: Wed Sep 19 15:52:53 IST 2018
[INFO] Final Memory: 19M/67M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project formsfx-core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[24,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[25,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[26,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[27,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[26,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[27,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[28,20] package javafx.event does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[29,20] package javafx.event does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[46,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[47,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[52,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[56,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[24,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[25,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[26,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[27,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[28,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[29,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[30,26] package javafx.collections does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[31,26] package javafx.collections does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[136,12] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[148,12] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Section.java:[167,12] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Section
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[42,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[43,21] cannot find symbol
[ERROR] symbol:   class ListProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[44,21] cannot find symbol
[ERROR] symbol:   class IntegerProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[102,12] cannot find symbol
[ERROR] symbol:   class IntegerProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[110,12] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[114,12] cannot find symbol
[ERROR] symbol:   class ObservableList
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Element.java:[118,12] cannot find symbol
[ERROR] symbol:   class ListProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Element<E>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[54,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[55,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[63,23] cannot find symbol
[ERROR] symbol:   class EventType
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[24,20] package javafx.event does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[25,20] package javafx.event does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[32,39] cannot find symbol
[ERROR] symbol: class Event
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[63,50] cannot find symbol
[ERROR] symbol:   class EventHandler
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[195,12] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[203,12] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[221,34] cannot find symbol
[ERROR] symbol:   class EventType
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[221,67] cannot find symbol
[ERROR] symbol:   class EventHandler
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[245,37] cannot find symbol
[ERROR] symbol:   class EventType
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Group.java:[245,70] cannot find symbol
[ERROR] symbol:   class EventHandler
[ERROR] location: class com.dlsc.formsfx.model.structure.Group
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[36,25] cannot find symbol
[ERROR] symbol:   class EventType
[ERROR] location: class com.dlsc.formsfx.model.event.GroupEvent
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[41,25] cannot find symbol
[ERROR] symbol:   class EventType
[ERROR] location: class com.dlsc.formsfx.model.event.GroupEvent
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[59,24] cannot find symbol
[ERROR] symbol:   class EventType
[ERROR] location: class com.dlsc.formsfx.model.event.GroupEvent
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/event/GroupEvent.java:[59,44] cannot find symbol
[ERROR] symbol:   class Event
[ERROR] location: class com.dlsc.formsfx.model.event.GroupEvent
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/IntegerField.java:[25,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/IntegerField.java:[26,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[29,20] package javafx.beans does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[30,28] package javafx.beans.binding does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[31,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[32,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[33,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[34,19] package javafx.util does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[27,20] package javafx.beans does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[28,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[29,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[30,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[31,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[32,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[33,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[34,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[35,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[36,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[37,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[38,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[39,26] package javafx.collections does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[44,26] package javafx.collections does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[45,20] package javafx.event does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[46,20] package javafx.event does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[47,20] package javafx.scene does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[48,28] package javafx.scene.control does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[49,28] package javafx.scene.control does not exist
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/IntegerField.java:[35,45] cannot find symbol
[ERROR] symbol: class IntegerProperty
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[48,43] cannot find symbol
[ERROR] symbol: class Property
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/IntegerField.java:[47,28] cannot find symbol
[ERROR] symbol:   class SimpleIntegerProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.IntegerField
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/IntegerField.java:[47,65] cannot find symbol
[ERROR] symbol:   class SimpleIntegerProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.IntegerField
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[64,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[80,15] cannot find symbol
[ERROR] symbol:   class StringConverter
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[93,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[94,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[99,19] cannot find symbol
[ERROR] symbol:   class InvalidationListener
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[172,21] cannot find symbol
[ERROR] symbol:   class StringConverter
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[191,21] cannot find symbol
[ERROR] symbol:   class StringConverter
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/DataField.java:[450,12] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.DataField<P,V,F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[80,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[81,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[90,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[91,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[100,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[101,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[107,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[108,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[109,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[110,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[116,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[117,21] cannot find symbol
[ERROR] symbol:   class BooleanProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[122,21] cannot find symbol
[ERROR] symbol:   class StringProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] /C:/Users/chandu/Downloads/formsfx-master/formsfx-core/src/main/java/com/dlsc/formsfx/model/structure/Field.java:[123,21] cannot find symbol
[ERROR] symbol:   class ListProperty
[ERROR] location: class com.dlsc.formsfx.model.structure.Field<F>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by dlemmermann** [comment]
It looks like you are not using the master-11 branch.
