### ISSUE TITLE
Any plans to publish the project to Maven?

### ISSUE THREAD

**Issue by danielpeintner** [dlemmermann/formsfx#5]
For integration in build systems it would be very handy to have a referenceable maven group/artifactID.

BTW, Thanks for your contribution!

**Comment by danielpeintner** [comment]
Great, thanks!

**Comment by dlemmermann** [comment]
The project can now be found on jcentral. 

```xml
<repositories>
  <repository>
    <id>jcenter</id>
    <url>http://jcenter.bintray.com</url>
  </repository>
</repositories>

<dependency>
  <groupId>com.dlsc.formsfx</groupId>
  <artifactId>formsfx-core</artifactId>
  <version>1.0</version>
</dependency>
```

I hope that it will eventually also arrive on maven central but I am still waiting for them to create an account for me.
